name: Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/suri-backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/suri-backend

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/suri-frontend -f ./frontend/Dockerfile.prod ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/suri-frontend